version = 0.1
[default.deploy.parameters]
stack_name = "cloudformation-basic-site"
resolve_s3 = true
s3_prefix = "cloudformation-basic-site"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
fail_on_empty_changeset = false
